### ISSUE TITLE
ImportError: cannot import name 'F1' from 'torchmetrics' (/app/anaconda3/lib/python3.7/site-packages/torchmetrics/__init__.py)

### ISSUE THREAD

**Issue by aiXia121** [kkoutini/PaSST#23]
python ex_openmic.py
Traceback (most recent call last):
  File "ex_openmic.py", line 5, in <module>
    from pytorch_lightning.callbacks import ModelCheckpoint
  File "/root/work_project_2021/project_music2video/PaSST/src/pytorch-lightning/pytorch_lightning/__init__.py", line 65, in <module>
    from pytorch_lightning import metrics
  File "/root/work_project_2021/project_music2video/PaSST/src/pytorch-lightning/pytorch_lightning/metrics/__init__.py", line 16, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/root/work_project_2021/project_music2video/PaSST/src/pytorch-lightning/pytorch_lightning/metrics/classification/__init__.py", line 19, in <module>
    from pytorch_lightning.metrics.classification.f_beta import F1, FBeta  # noqa: F401
  File "/root/work_project_2021/project_music2video/PaSST/src/pytorch-lightning/pytorch_lightning/metrics/classification/f_beta.py", line 16, in <module>
    from torchmetrics import F1 as _F1
ImportError: cannot import name 'F1' from 'torchmetrics' (/app/anaconda3/lib/python3.7/site-packages/torchmetrics/__init__.py)

envs:
Name: torch
Version: 1.12.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /app/anaconda3/lib/python3.7/site-packages
Requires: typing-extensions
Required-by: torchvision, torchmetrics, torchaudio, timm, test-tube, Ba3l, pytorch-lightning

**Comment by Ludvig-Joborn** [comment]
I was able to solve this issue by downgrading Torchmetrics to version 0.6.2:
```bash
pip install torchmetrics==0.6.2
```
In torchmetrics 0.7.0, some metrics were renamed. For example, F1 was changed to F1Score. The authors haven't updated ```piplist.txt``` to reflect this, using version 0.9.3 instead.
